---
collections:
  - name: ansible.posix
  - name: community.crypto
  - name: vmware.vmware_rest
  - name: cloud.terraform
  - name: community.docker
  - name: community.esxi
    type: git
    source: https://github.com/djdanielsson/ansible-esxi.git
  - name: redhat.satellite_operations
