---
# defaults file for terraform
rhel8_vms:
  - name: controller1
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
    power: off # noqa yaml[truthy]
    notes: "automationcontroller"
  - name: hub1
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
    power: off # noqa yaml[truthy]
    notes: "automationhub"
  - name: aapdb
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 2
    power: off # noqa yaml[truthy]
    notes: "database"
  - name: eda
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
    power: off # noqa yaml[truthy]
    notes: "automationedacontroller"
  - name: testrhel8
    fqdn: lab.danielsson.us.com
    mem: 2
    cpu: 2
    power: off # noqa yaml[truthy]

rhel9_vms:
  - name: vault
    fqdn: lab.danielsson.us.com
    mem: 2
    cpu: 2
    power: off # noqa yaml[truthy]
  - name: aap
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
  - name: crc
    fqdn: lab.danielsson.us.com
    mem: 16
    cpu: 8

fedora_vms:
  - name: testfedora
    fqdn: lab.danielsson.us.com
    mem: 2
    cpu: 2
    power: off # noqa yaml[truthy]
    #  - name: k3s
    #    fqdn: lab.danielsson.us.com
    #    mem: 8
    #    cpu: 8

ubuntu_vms:
  - name: portainer
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
  - name: portainer2
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
    power: off # noqa yaml[truthy]
  - name: kasm
    fqdn: lab.danielsson.us.com
    mem: 4
    cpu: 4
    disk_size: 100
    power: off # noqa yaml[truthy]
  - name: testubuntu
    fqdn: lab.danielsson.us.com
    mem: 2
    cpu: 2
    power: off # noqa yaml[truthy]
  - name: testubuntu2
    power: off # noqa yaml[truthy]
  - name: k3s
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
  - name: k3s1
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
    power: off # noqa yaml[truthy]
  - name: k3s2
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
    power: off # noqa yaml[truthy]
  - name: k3s3
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
    power: off # noqa yaml[truthy]

terraform_templates:
  - src: ubuntu.tf.j2
    dest: ubuntu.tf
  - src: provider.tf.j2
    dest: provider.tf
  - src: rhel8.tf.j2
    dest: rhel8.tf
  - src: rhel9.tf.j2
    dest: rhel9.tf
    #  - src: fedora.tf.j2
    #    dest: fedora.tf

cloud_files:
  - name: ubuntu-cloud.tpl
  - name: fedora-cloud.tpl
  - name: rhel9-cloud.tpl
  - name: rhel8-cloud.tpl
...
