---
# defaults file for terraform
rhel8_vms:
  - name: controller1
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
    notes: "automationcontroller"
  - name: hub1
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
    notes: "automationhub"
  - name: aapdb
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 2
    notes: "database"
  - name: eda
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
    notes: "automationedacontroller"
  - name: testrhel8
    fqdn: lab.danielsson.us.com
    mem: 2
    cpu: 2

rhel9_vms:
  - name: vault
    fqdn: lab.danielsson.us.com
    mem: 2
    cpu: 2

fedora_vms:
  - name: testfedora
    fqdn: lab.danielsson.us.com
    mem: 2
    cpu: 2

ubuntu_vms:
  - name: k3s
    fqdn: lab.danielsson.us.com
    mem: 8
    cpu: 8
  - name: kasm
    fqdn: lab.danielsson.us.com
    mem: 4
    cpu: 4
    disk_size: 100
  - name: testubuntu
    fqdn: lab.danielsson.us.com
    mem: 2
    cpu: 2
  - name: testubuntu2

terraform_templates:
  - src: ubuntu.tf.j2
    dest: ubuntu.tf
  - src: provider.tf.j2
    dest: provider.tf
  - src: rhel8.tf.j2
    dest: rhel8.tf
  - src: rhel9.tf.j2
    dest: rhel9.tf
  - src: fedora.tf.j2
    dest: fedora.tf

cloud_files:
  - name: ubuntu-cloud.tpl
  - name: fedora-cloud.tpl
  - name: rhel9-cloud.tpl
  - name: rhel8-cloud.tpl
...
