---
# tasks file for download_qcow2
- name: Login to Red Hat APIs
  ansible.builtin.uri:
    url: "{{ login_url }}"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ api_token }}"
  register: __r_login

- name: Collecting the available options
  ansible.builtin.uri:
    url: "{{ image_url }}"
    method: GET
    return_content: true
    headers:
      Authorization: "Bearer {{ __r_login.json.access_token }}"
  register: __r_images_output

- name: Simplify the list of possible downloads
  ansible.builtin.set_fact:
    __cf_images: "{{ __r_images_output.json.body | sort(attribute='datePublished', reverse=true) }}"

- name: Downloading {{ item.filename }}
  ansible.builtin.get_url:
    url: "{{ item.downloadHref }}"
    dest: "{{ setup_down_dest_dir }}/{{ item.filename }}"
    headers:
      Authorization: "Bearer {{ __r_login.json.access_token }}"
  when: image_name is match(item.filename)
  loop: "{{ __cf_images }}"
...
