---
- name: Create temporary randomly named directory
  ansible.builtin.tempfile:
    state: directory
  register: tmp_dir
  notify:
    - Delete temporary directory

- name: Download and unpack tar.gz file
  ansible.builtin.unarchive:
    src: "https://kasm-static-content.s3.amazonaws.com/kasm_release_1.12.0.d4fd8a.tar.gz"
    dest: "{{ tmp_dir.path }}"
    remote_src: true
    mode: "0755"
  notify:
    - Delete temporary directory

- name: Run bash script
  ansible.builtin.command: "{{ tmp_dir.path }}/kasm_release/install.sh -e -H --admin-password {{ kasm_admin_pass }} --user-password {{ kasm_user_pass }}"
  changed_when: true
  become: true
...
