---
# handlers file for portainer
- name: Enable docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Enable containerd
  ansible.builtin.service:
    name: containerd
    enabled: true
    state: started
...
