---
- name: Capture POSTs from satellite
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.json_filter:
            exclude_keys: ['sender', 'owner']
        - ansible.eda.dashes_to_underscores:

  rules:
    - name: test
      condition: event.payload is defined
      action:
        debug:
...
