---
- name: Install Satellite
  hosts: all
  roles:
    - role: redhat.satellite_operations.installer
      vars:
        satellite_installer_scenario: satellite
        satellite_installer_options:
          - '--foreman-initial-organization "lab"'
          - '--foreman-initial-admin-password Password1234!'
...
