---
- name: Install Satellite
  hosts: all
  roles:
    - role: redhat.satellite_operations.installer
      vars:
        satellite_installer_scenario: satellite
        satellite_installer_package: satellite
        satellite_installer_options:
          - '--foreman-initial-organization "lab"'
          - '--foreman-initial-location "home"'
          - '--foreman-initial-admin-password Password1234!'
          - '--foreman-proxy-dns true'
          - '--foreman-proxy-dns-managed true'
          - '--foreman-proxy-dns-interface eth0'
          - '--foreman-proxy-dns-zone lab.danielsson.us.com'
          - '--foreman-proxy-dns-reverse 1.168.192.in-addr.arpa'
          - '--foreman-proxy-dhcp true'
          - '--foreman-proxy-dhcp-managed true'
          - '--foreman-proxy-dhcp-interface eth0'
          # - '--foreman-proxy-dhcp-additional-interfaces eth1'
          # - '--foreman-proxy-dhcp-additional-interfaces eth2'
          - '--foreman-proxy-dhcp-range "192.168.1.100 192.168.1.150"'
          - '--foreman-proxy-dhcp-gateway 192.168.1.1'
          - '--foreman-proxy-dhcp-nameservers 192.168.1.37'
          - '--foreman-proxy-tftp true'
          - '--foreman-proxy-tftp-managed true'
-         - '--foreman-proxy-tftp-servername 192.168.1.37'
...
